demo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tree/', include('tree.urls')),
    path('admin/', admin.site.urls),
]

tree/urls.py
from django.urls import path

from . import views

app_name = 'tree'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all/', views.AllView.as_view(), name='all'),
    path('childs/', views.ChildView.as_view(), name='childs'),
]

tree/models.py
from django.db import models


class Tree(models.Model):
    parent = models.ForeignKey('self', models.CASCADE, null=True,
                               verbose_name='Родитель')
    name = models.CharField(max_length=255, verbose_name='Название')

    def generate_tree(self, key, name=None):
        """Генерация дерева по id"""
        
        if key:
            try:
                return {
                    'id': key,
                    'name': name if name else Tree.objects.get(pk=key).name,
                    'children': [self.generate_tree(self, x.id, x.name) for x
                                 in Tree.objects.filter(parent=key)]
                }
            except models.ObjectDoesNotExist:
                return 'Ключ отстутсвует в базе'
        else:
            return 'Пустой ключ'

    def generate_tree_optimized(self, key):
        """Генерация дерева по id (меньшее кол-во запросов к базе)"""

        def flat_list(data):
            """Развертывание вложенных списков"""
            return [
                item for sublist in data for item in sublist
            ]

        def create_record(tree_list):
            """Преобразование списка объектов Tree в список словарей"""
            result = []

            def create(node):
                """Преобразование объекта Tree в словарь"""
                return {
                    'id': node.id,
                    'name': node.name,
                    'children': [create(x) for x in tree_list if
                                 x.parent_id
                                 == node.id]
                }
            for tree in tree_list:
                result.append(create(tree))
            return result[0]

        def generate(node, data=[]):
            if node:
                if isinstance(node, int):
                    qs = Tree.objects.filter(id=node)
                    ds = list(qs)
                    data.append(ds)
                    return generate(qs, data)
                else:
                    qs = Tree.objects.filter(parent__in=node)
                    if qs:
                        ds = list(qs)
                        data.append(ds)
                        return generate(qs, data)
                    else:
                        return create_record(flat_list(data))
        return generate(key)

tree/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, Http404

from .models import Tree


class IndexView(generic.View):
    template_name = 'tree/index.html'
    
    def get(self, request):
        return render(request, 'tree/index.html')


class AllView(generic.ListView):
    """
    Отображение всех данных из модели
    Возможно использование JSON вместо шаблона
    """

    model = Tree
    template_name = 'tree/all.html'
    context_object_name = 'tree_list'

    def get_queryset(self):
        return (Tree.generate_tree(Tree, x.id) for x in Tree.objects.filter(parent=None))

    
class ChildView(generic.View):
    """
    Отображение потомков по выбранному элементу
    """
    model = Tree
    template_name = 'tree/childs.html'
    context_object_name = 'child'
    node = None
    
    def get_queryset(self):
        return Tree.generate_tree(Tree, self.node)
    
    def post(self, request):
        self.node = request.POST['child']
        return HttpResponse(str(Tree.generate_tree(Tree, self.node)))

tree/templates/tree/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Построение по всем данным из модели</title>
</head>
<body>
    {% if tree_list %}
    <ul>
    {% for tree in tree_list %}
        <li>{{ tree }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет деревьев для отображения</p>
{% endif %}
</body>
</html>

tree/templates/tree/childs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Построение по ключу</title>
</head>
<body>
</form>
    {% if child %}
        <p>{{ child }}</p>>
    {% endif %}
</body>
</html>

tree/templates/tree/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выбор функции</title>
</head>
<body>
    <ul>
		<li><a href="{% url 'tree:all' %}">Сгенерировать все деревья</a></li>
        <li><form action="{% url 'tree:childs' %}" method="post">{% csrf_token %}
            <label for="child">ID элемента: </label>
            <input id="child" type="number" name="child" min="1" value="{{ node }}">
            <input type="submit" value="OK">
</form></li>
    </ul>
</body>
</html>